# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pr:
- master

pool:
  vmImage: 'macos-latest'

#Your build pipeline references a secret variable named ‘P12password’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘SDK’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘Configuration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

steps:
- script: |
   git submodule update --init
  displayName: 'Git submodule update'

- task: Xcode@5
  displayName: 'Xcode clean test'
  inputs:
    actions: 'clean test'
    configuration: Debug
    sdk: iphonesimulator
    xcWorkspacePath: sdk.xcworkspace
    scheme: VCServices
    xcodeVersion: specifyPath
    xcodeDeveloperDir: '/Applications/Xcode_12.2.app'
    signingOption: default
    destinationPlatformOption: iOS
    destinationSimulators: 'iPhone 11'
    args: '-derivedDataPath output/derivedData -enableCodeCoverage YES'
    publishJUnitResults: true